import { createSlice } from "@reduxjs/toolkit";

// const type payloadProp = {
//   formPayload : {
//     [key]:{
//       payload:{
//         [key]:{
//           isRequired:Boolean,
//           value:string | number,
//           type:string,
//           options:string[],
//           isAdvanceoption:Boolean,
//           hide:Boolean,
//           min:number,
//           max:number,
//           isFloat:boolean
//           isRandomizefn:fn
//         }
//       }
//     }
//   }
// }
const initialState = {
  formPayload: {
    "prithivMLmods/IMAGINEO-4K": {
      payloadType: "string", // if withKeys then use prompt as it is
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        collage_style: {
          value: "Hi-Res",
          type: "radio",
          options: [
            "Hi-Res",
            "B & W",
            "Polaroid",
            "Watercolor",
            "Cinematic",
            "Nostalgic",
            "Vintage",
            "Scrapbook",
            "NeoNGlow",
            "Geometric",
            "Thematic",
            "Cherry",
            "Fuchsia",
            "Pop",
            "Violet",
            "Sea Blue",
            "Sea Green",
            "Mustard",
            "Amber",
            "Pomelo",
            "Peppermint",
            "Mystic",
            "Pastel",
            "Coral",
            "No Style",
          ],
        }, //choices
        filter_name: {
          value: "Zero filter",
          type: "radio",
          options: [
            "Vivid",
            "Playa",
            "Desert",
            "West",
            "Blush",
            "Minimalist",
            "Zero filter",
          ],
        },
        grid_size: {
          value: "1x1",
          type: "dropdown",
          options: ["1x1", "2x1", "1x2", "2x2", "2x3", "3x2", "3x3"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "mukaist/Midjourney": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "mukaist/DALLE-4K": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "Boboiazumi/animagine-xl-3.1": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        seed: {
          isAdvanceoption: true,
          value: Math.floor(Math.random() * (2147483647 + 1)),
          type: "number",
          isRandomize: true,
        },
        custom_width: {
          isAdvanceoption: true,
          value: 1024,
          type: "number",
          min: 512,
          max: 2048,
        },
        custom_height: {
          isAdvanceoption: true,
          value: 1024,
          type: "number",
          min: 512,
          max: 2048,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 7,
          type: "slider",
          min: 1,
          max: 12,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 28,
          type: "slider",
          min: 1,
          max: 50,
        },
        sampler: {
          value: "Euler a",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Karras",
            "Euler",
            "Euler a",
            "DDIM",
          ],
        },
        aspect_ratio_selector: {
          value: "896 x 1152",
          options: [
            "1024 x 1024",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
        style_selector: {
          value: "(None)",
          type: "radio",
          options: [
            "(None)",
            "Cinematic",
            "Photographic",
            "Anime",
            "Manga",
            "Digital Art",
            "Pixel art",
            "Fantasy art",
            "Neonpunk",
            "3D Model",
          ],
        },
        quality_selector: {
          type: "dropdown",
          value: "Standard v3.1",
          options: [
            "(None)",
            "Standard v3.0",
            "Standard v3.1",
            "Light v3.1",
            "Heavy v3.1",
          ],
        },
        use_upscaler: { type: "checkbox", value: false }, // boolean  in 'Use Upscaler' Checkbox component
        upscaler_strength: {
          type: "slider",
          value: 0.5,
          hide: true,
          min: 0,
          max: 1,
          step: 0.1,
          isFloat: true,
        }, // image strength
        upscale_by: {
          type: "slider",
          value: 1,
          min: 1,
          max: 1.5,
          step: 0.1,
          isFloat: true,
        },
        add_quality_tags: {
          type: "checkbox",
          value: true,
        },
        isImg2Img: {
          type: "checkbox",
          value: false,
          hide: true,
        },
        img_path: {
          type: "imageUpload",
          hide: true,
          value: null,
        },
        img2img_strength: {
          value: 0.5,
          type: "slider",
          min: 0,
          max: 1,
          hide: true,
        },
      },
    },
    "prodia/sdxl-stable-diffusion-xl": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "(deformed eyes, nose, ears, nose), bad anatomy, ugly",
          type: "textarea",
        },
        stable_diffusion_checkpoints: {
          value: "sd_xl_base_1.0.safetensors [be9edd61]",
          type: "dropdown",
          options: [
            "animagineXLV3_v30.safetensors [75f2f05b]",
            "devlishphotorealism_sdxl15.safetensors [77cba69f]",
            "dreamshaperXL10_alpha2.safetensors [c8afe2ef]",
            "dynavisionXL_0411.safetensors [c39cc051]",
            "juggernautXL_v45.safetensors [e75f5471]",
            "realismEngineSDXL_v10.safetensors [af771c3f]",
            "realvisxlV40.safetensors [f7fdcb51]",
            "sd_xl_base_1.0.safetensors [be9edd61]",
            "sd_xl_base_1.0_inpainting_0.1.safetensors [5679a81a]",
            "turbovisionXL_v431.safetensors [78890989]",
          ],
        },
        sampling_step: {
          value: 20,
          type: "slider",
          isAdvanceoption: true,
          min: 1,
          max: 25,
        },
        sampler: {
          value: "DPM++ 2M Karras",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Exponential",
            "DPM++ 2M SDE Karras",
            "Euler a",
            "Euler",
            "LMS",
            "Heun",
            "DPM2",
            "DPM2 a",
            "DPM++ 2S a",
            "DPM++ 2M",
            "DPM++ SDE",
            "DPM++ 2M SDE",
            "DPM++ 2M SDE Heun",
            "DPM++ 2M SDE Heun Karras",
            "DPM++ 2M SDE Heun Exponential",
            "DPM++ 3M SDE",
            "DPM++ 3M SDE Karras",
            "DPM++ 3M SDE Exponential",
            "DPM fast",
            "DPM adaptive",
            "LMS Karras",
            "DPM2 Karras",
            "DPM2 a Karras",
            "DPM++ 2S a Karras",
            "Restart",
            "DDIM",
            "PLMS",
          ],
        },
        cfg_scale: {
          value: 7,
          type: "slider",
          isAdvanceoption: true,
          min: 1,
          max: 20,
        },
        width: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        height: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        seed: {
          type: "number",
          isAdvanceoption: true,
          value: -1,
        },
      },
    },
    "KingNish/SDXL-Flash": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 3,
          type: "slider",
          step: 0.1,
          min: 0.1,
          max: 6,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 8,
          type: "slider",
          min: 1,
          max: 15,
        },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "Akimitsujiro/Stable-Diffusion-XL": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          value: 512,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          value: 512,
          type: "slider",
          min: 512,
          max: 4096,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 7,
          type: "slider",
          step: 0.1,
          min: 0.1,
          max: 12,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 28,
          type: "slider",
          min: 1,
          max: 50,
        },
        sampler: {
          value: "Euler a",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Karras",
            "Euler",
            "Euler a",
            "DDIM",
            "DPM++ 2S a",
            "Heun",
            "DPM fast",
          ],
        },
        aspect_ratio_selector: {
          value: "896 x 1152",
          options: [
            "1024 x 1024",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
        collage_style: {
          value: "(None)",
          type: "radio",
          options: [
            "(None)",
            "Cinematic",
            "Photographic",
            "Anime",
            "Manga",
            "Digital Art",
            "Pixel art",
            "Fantasy art",
            "Neonpunk",
            "3D Model",
            "Analog Film",
            "Comics Book",
            "Line Art",
            "Illustration | Anime",
            "Illustration | Chibi",
            "Design | Avatar",
            "Glitch",
            "Pencil",
            "Texture",
            "Advertising",
            "Food Photography",
            "Real Estate",
            "Abstract",
            "Cubist",
            "Graffiti",
            "Hyperrealism",
            "Impressionist",
            "Pointillism",
            "Pop Art",
            "Psychedelic",
            "Renaissance",
            "Steampunk",
            "Surrealist",
            "Typography",
            "Watercolor",
            "Fighting Game",
            "GTA",
            "Super Mario",
            "Minecraft",
            "Pokémon",
            "Retro Arcade",
            "Retro Game",
            "RPG Fantasy Game",
            "Strategy Game",
            "Street Fighter",
            "Legend of Zelda",
            "Architectural",
            "Disco",
            "Dreamscape",
            "Dystopian",
            "Fairy Tale",
            "Gothic",
            "Grunge",
            "Horror",
            "Minimalist",
            "Monochrome",
            "Nautical",
            "Space",
            "Stained Glass",
            "Techwear Fashion",
            "Tribal",
            "Zentangle",
            "Collage",
            "Flat Papercut",
            "Kirigami",
            "Paper Mache",
            "Paper Quilling",
            "Papercut Collage",
            "Papercut Shadow Box",
            "Stacked Papercut",
            "Thick Layered Papercut",
            "Alien",
            "Film Noir",
            "HDR",
            "Long Exposure",
            "Neon Noir",
            "Silhouette",
            "Tilt-Shift",
          ],
        },
        quality_selector: {
          type: "dropdown",
          value: "Standard v3.1",
          options: [
            "(None)",
            "Standard v3.0",
            "Standard v3.1",
            "Light v3.1",
            "Heavy v3.1",
            "NSFW",
          ],
        },
        use_upscaler: { type: "checkbox", value: false }, // boolean  in 'Use Upscaler' Checkbox component
        upscaler_strength: {
          type: "slider",
          value: 0.5,
          // hide: true,
          min: 0,
          max: 1,
          step: 0.5,
          isFloat: true,
        },
        upscale_by: {
          type: "slider",
          value: 1,
          min: 1,
          max: 1.5,
          step: 0.1,
          isFloat: true,
        },
        add_quality_tags: {
          type: "checkbox",
          value: true,
        },
      },
    },
    "prithivMLmods/EPIC-REALISM": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        unknownParam: {
          type: "unknown",
          value: true,
          hide: true,
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        unknownParam2: {
          type: "unknown",
          value: 3,
          hide: true,
        },
        unknownParam3: {
          type: "unknown",
          value: true,
          hide: true,
        },
        aspect_ratio_selector: {
          value: "3840 x 2160",
          hide: true,
          options: [
            "3840 x 2160",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
      },
    },
    "John6666/votepurchase-multiple-model": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(low quality, worst quality:1.2), very displeasing, watermark, signature, ugly",
          type: "textarea",
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          // isRandomize: true,
          hide: true,
        },
        randomize_seed: {
          hide: true,
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
        width: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        height: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 7,
          type: "slider",
          min: 0,
          max: 30,
          step: 0.1,
          isFloat: true,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 28,
          type: "slider",
          min: 1,
          max: 100,
        },
        model: {
          value: "votepurchase/animagine-xl-3.1",
          type: "dropdown",
          options: [
            "votepurchase/animagine-xl-3.1",
            "votepurchase/NSFW-GEN-ANIME-v2",
            "votepurchase/kivotos-xl-2.0",
            "votepurchase/holodayo-xl-2.1",
            "votepurchase/ponyDiffusionV6XL",
            "votepurchase/AnythingXL_xl",
            "votepurchase/7thAnimeXLPonyA_v10",
            "votepurchase/ChilloutMix",
            "votepurchase/NovelAIRemix",
            "votepurchase/NSFW-gen-v2",
            "votepurchase/PerfectDeliberate-Anime_v2",
            "votepurchase/realpony-xl",
            "votepurchase/artiwaifu-diffusion-1.0",
            "votepurchase/Starry-XL-v5.2",
            "votepurchase/Yaki-Dofu-Mix",
            "votepurchase/ebara-pony-v1-sdxl",
            "votepurchase/waiANIMIXPONYXL_v10",
            "votepurchase/counterfeitV30_v30",
            "votepurchase/ebara-pony",
            "votepurchase/Realistic_Vision_V1.4",
            "votepurchase/pony",
            "votepurchase/ponymatureSDXL_ponyeclipse10",
            "votepurchase/waiREALMIX_v70",
            "votepurchase/waiREALCN_v10",
            "votepurchase/PVCStyleModelMovable_pony151",
            "votepurchase/PVCStyleModelMovable_beta27Realistic",
            "votepurchase/PVCStyleModelFantasy_beta12",
            "votepurchase/pvcxl-v1-lora",
            "votepurchase/Realistic_Vision_V2.0",
            "votepurchase/RealVisXL_V4.0",
            "votepurchase/juggernautXL_hyper_8step_sfw",
            "votepurchase/ponyRealism_v21MainVAE",
            "stabilityai/stable-diffusion-xl-base-1.0",
            "cagliostrolab/animagine-xl-3.1",
            "misri/epicrealismXL_v7FinalDestination",
            "misri/juggernautXL_juggernautX",
            "misri/zavychromaxl_v80",
            "SG161222/RealVisXL_V4.0",
            "misri/newrealityxlAllInOne_Newreality40",
            "eienmojiki/Anything-XL",
            "eienmojiki/Starry-XL-v5.2",
            "gsdf/CounterfeitXL",
            "kitty7779/ponyDiffusionV6XL",
            "yodayo-ai/kivotos-xl-2.0",
            "yodayo-ai/holodayo-xl-2.1",
            "digiplay/majicMIX_sombre_v2",
            "digiplay/majicMIX_realistic_v6",
            "digiplay/majicMIX_realistic_v7",
            "digiplay/DreamShaper_8",
            "digiplay/BeautifulArt_v1",
            "digiplay/DarkSushi2.5D_v1",
            "digiplay/darkphoenix3D_v1.1",
            "digiplay/BeenYouLiteL11_diffusers",
            "rubbrband/revAnimated_v2Rebirth",
            "youknownothing/cyberrealistic_v50",
            "Meina/MeinaMix_V11",
            "Meina/MeinaUnreal_V5",
            "Meina/MeinaPastel_V7",
            "rubbrband/realcartoon3d_v16",
            "rubbrband/realcartoonRealistic_v14",
            "KBlueLeaf/Kohaku-XL-Epsilon-rev2",
            "KBlueLeaf/Kohaku-XL-Epsilon-rev3",
            "kayfahaarukku/UrangDiffusion-1.1",
            "Raelina/Rae-Diffusion-XL-V2",
            "Raelina/Raemu-XL-V4",
            "votepurchase/peganaMERGE_v30",
            "votepurchase/valiantStallion_v30",
            "John6666/wai-ani-nsfw-ponyxl-v7-sdxl",
            "John6666/hamef-kawaii-mix-type39deep-sdxl",
            "John6666/mid-travel-v1-sdxl",
            "John6666/brutal-xl-v01-sdxl",
            "John6666/smooth-hassaku-authaku-mix-v3-sdxl",
            "John6666/catpony-ani-v2-sdxl",
            "John6666/sweet-mix-xl-v11-sdxl",
            "John6666/mklan-aio-nsfw-aio-nextgen-xl-sdxl",
            "John6666/perfect-rsb-mix-pony-real-anime-sfw-nsfw-v71-sdxl",
            "John6666/flower-mix-cherry-xl-v5-sdxl",
            "John6666/koji-pony-mix-v1-sdxl",
            "John6666/monster-coffee-celsius-mix-v1-sdxl",
            "John6666/darkmix-pony-v1-sdxl",
            "John6666/leekai-leekyfix-sdxl",
            "John6666/rdxl-smash-bros-pony2-sdxl",
            "John6666/sakushi-mix-sdxl",
            "John6666/knk-cieloblend-ponyv6-v1-sdxl",
            "John6666/comradeship-xl-v9m-sdxl",
            "John6666/duchaiten-gameart-unrealenginev10-sdxl",
            "John6666/duchaiten-pony-xl-no-score-v51fix-sdxl",
            "John6666/granfinos-mirage-pony-v2-sdxl",
            "John6666/authaku-mix-otaku-mix-sdxl",
            "John6666/hda-matrix-copdxl-v1-sdxl",
            "John6666/mistoon-anime-ponyalpha-sdxl",
            "John6666/hamef-kawaii-mix-type3deep-sdxl",
            "John6666/urang-diffusion-v12-sdxl",
            "John6666/raemora-xl-v3-sdxl",
            "John6666/white-unicorn-v3-sdxl",
            "John6666/venom-spell-v1-sdxl",
            "John6666/grimoire-p0666-sdxl",
            "John6666/peroperositai-v1-sdxl",
            "John6666/catloaf-v1-sdxl",
            "John6666/kojono-pony-checkpoint-ponyv01-sdxl",
            "John6666/night-heavy-industry-v1-sdxl",
            "John6666/mistoon-xl-copper-v20fast-sdxl",
            "John6666/30104-v21-sdxl",
            "John6666/mix-photoreal-stable-xl-stable4-sdxl",
            "John6666/perillanium-cem-sdxl",
            "John6666/perillanium-v1-sdxl",
            "John6666/perillanium-seft-sdxl",
            "John6666/perillanium-ccm-sdxl",
            "John6666/wai-ani-hentai-pony-v3-sdxl",
            "John6666/cosplay-serendipity-pny-v5-sdxl",
            "John6666/ytcyponyxl-v1-sdxl",
            "John6666/wai-celluloid-style-v1-sdxl",
            "John6666/sanaexl-anime-v08-sdxl",
            "John6666/comradeship-xl-v12t3wdv01-sdxl",
            "John6666/flower-mix-berry-xl-v1-sdxl",
            "John6666/rain-cloud-v1-sdxl",
            "John6666/daisyxl-v1-sdxl",
            "John6666/prefect-pony-xl-v2-cleaned-style-sdxl",
            "John6666/toonystark-korean-webtoon-xl-pony10-sdxl",
            "John6666/bemypony-photo3-sdxl",
            "John6666/mid-sdxl-sdxl",
            "John6666/perfect-rsb-mixl-xl-real-anime-sfw-nsfw-v1-sdxl",
            "John6666/comradeship-xl-v12t1wdv01-sdxl",
            "John6666/wdv-test-v01-sdxl",
            "John6666/anipony-xl-v23-sdxl",
            "John6666/evo-merge-sdxlpony20-sdxl",
            "John6666/red-blue-fantasy-pony-sdxl",
            "John6666/nai3like-diffusion-v1-sdxl",
            "John6666/savsdxl-v6-sdxl",
            "John6666/ohara-pdxl-v4-sdxl",
            "John6666/8528xl-v1-sdxl",
            "John6666/makino540mix-v1-sdxl",
            "John6666/bqt-v1-sdxl",
            "John6666/gusgenm-pony-sp1-sdxl",
            "John6666/granfinos-mirage-pony-v1-sdxl",
            "John6666/fenrisxl-v18-thl-sdxl",
            "John6666/noah-mix-pony-2d25d-v5-sdxl",
            "John6666/wai-doll-cn-v3-sdxl",
            "John6666/rdxl-anime-sdxlpony7-sdxl",
            "John6666/anime-test-pony-v05-2d-sdxl",
            "John6666/bit-paint-v11-sdxl",
            "John6666/borscht-mix-final-sdxl",
            "John6666/soft-journey-v2-sdxl",
            "John6666/anime-from-hades-xl-v3-sdxl",
            "John6666/proteus-ani-mix-sdxl",
            "John6666/penny-diffusion-v1-v1-sdxl",
            "John6666/bemypony-photo2-sdxl",
            "John6666/obsidian-pdxl-v1-sdxl",
            "John6666/sasaki-pony-sdxl-ponyv05-sdxl",
            "John6666/hybrid-mix-sdxl-mod6finalbase-sdxl",
            "John6666/florag-pony-half-xl-sdxl",
            "John6666/knk-pony-merge-v2-sdxl",
            "John6666/t-ponynai3-v6-sdxl-bf16",
            "John6666/sasaki-pony-sdxl-ponyv01-sdxl",
            "John6666/nova-garden-v1-sdxl",
            "John6666/pvc-style-model-movable-pony-160-sdxl",
            "John6666/mugen-infinity-xl-v2-sdxl",
            "John6666/t3siincey-v08beta-sdxl",
            "John6666/urang-diffusion-v111-sdxl",
            "John6666/katayama-mix-xl-v2-sdxl",
            "John6666/anime-test-sdxl-v08-sdxl",
            "John6666/animagine-painting-v1-sdxl",
            "John6666/mix-photoreal-stable-xl-13final-sdxl",
            "John6666/comradeship-xl-v9se2-sdxl",
            "John6666/stardrop-xl-v3-sdxl",
            "John6666/snow4thtailautism-v1-sdxl",
            "John6666/cosplay-serendipity-pny-v4-sdxl",
            "John6666/ether-pdxl-a2b-sdxl",
            "John6666/t-ponynai3-v6-sdxl",
            "John6666/sdxrealistica-2-sdxl",
            "John6666/ani-real-xl-sdxl",
            "John6666/epicjourney-xl-v1-sdxl",
            "John6666/wow-xl-pd-wow-xl-7-sdxl",
            "John6666/clamsauce-v2-sdxl",
            "John6666/homemade-pony-v1-sdxl",
            "John6666/mmxl-v1-sdxl",
            "John6666/crucible-ring-v1-sdxl",
            "John6666/nova-anime-xl-pony-v3-sdxl",
            "John6666/catrush-v1-sdxl",
            "John6666/for-cute-xl-v1-sdxl",
            "John6666/sdxrealistica-1-sdxl",
            "John6666/0003-pony-epsilon-sdxl",
            "John6666/ragnarok-thl-sdxl-v101-sdxl",
            "John6666/mala-smooth-v2-sdxl",
            "John6666/js-confetti-v2-sdxl",
            "John6666/30104-v2-sdxl",
            "John6666/anime-test-pony-v31-sdxl",
            "John6666/sdxl-niji-seven-sdxl",
            "John6666/satpony-niji-v2-sdxl",
            "John6666/osorubeshi-ultra-anime-v1-sdxl",
            "John6666/proteus-v5-sdxl",
            "John6666/wai-c-v4-sdxl",
            "John6666/cosplay-serendipity-pny-v3-sdxl",
            "John6666/catpony-ani-v1-sdxl",
            "John6666/neta-art-xl-v2-sdxl",
            "John6666/smooth-hassaku-authaku-mix-v2-sdxl",
            "John6666/duchaiten-pony-xl-no-score-v5-sdxl",
            "John6666/god-pony-v21-sdxl",
            "John6666/stable-diffusion-xl-anime-final-final-sdxl",
            "John6666/tostxl-synthetic-anime-v1-sdxl",
            "John6666/30104-v1-sdxl",
            "John6666/wai-cute-v5-sdxl",
            "John6666/zhuangzi-mix-25d-v41-sdxl-brilliant-sdxl",
            "John6666/gusgenm-pony-v1-sdxl",
            "John6666/ohara-pdxl-v3-sdxl",
            "John6666/ultrium-v81-nsfwsfw-sdxl",
            "John6666/mocase-mix-v1-sdxl",
            "John6666/perfect-rsb-mix-multiuse-v61-sdxl",
            "John6666/grimoire-p0239-sdxl",
            "John6666/sifw-annihilation-xl-v2-sdxl",
            "John6666/any-kivotos-xl-for-lora-kivotosxl20v10-sdxl",
            "John6666/susamagine-xl-anime-v1-sdxl",
            "John6666/flower-mix-moon-xl-v2-sdxl",
            "John6666/davinci-v8-sdxl",
            "John6666/pixiv-pony-epita-mix-v1-sdxl",
            "John6666/pegana-merge-v3-sdxl",
            "John6666/inno-vision-v1-sdxl",
            "John6666/a80srpony-v1-sdxl",
            "John6666/stable-diffusion-xl-anime-final-v56-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v6-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v6-sdxl-spo-hyper",
            "John6666/mala-anime-mix-nsfw-pony-xl-v6-sdxl-spo-pcm",
            "John6666/pony-flat-mix-4l30-sdxl",
            "John6666/cosplay-serendipity-pny-v2-sdxl",
            "John6666/mugen-infinity-xl-v1-sdxl",
            "John6666/ak31-v1-sdxl",
            "John6666/anime-n-stuff-v1-sdxl",
            "John6666/bunny-mint-v3-ns-sdxl",
            "John6666/ether-pdxl-a2-sdxl",
            "John6666/ely-pony-xl-v15-sdxl",
            "John6666/defacta-xl-3-v3-animagine-sdxl",
            "John6666/smooth-hassaku-authaku-mix-v1-sdxl",
            "John6666/tsuki-v35-sdxl",
            "John6666/pys-gallery-anime-v24-sdxl",
            "John6666/noah-mix-pony-2d25d-v3-sdxl",
            "John6666/accretion-disc-xl-v1-sdxl",
            "John6666/stable-pony-v1-sdxl",
            "John6666/pinky-promise-pony-v1-sdxl",
            "John6666/cranberry-xl-v3-sdxl",
            "John6666/stanleys-triweekend-xxl-v5-stanleys-prancing-pony-sdxl",
            "John6666/sanaexl-anime-v1-sdxl",
            "John6666/defacta-xl-3-v3-sdxl",
            "John6666/jupiter-2dnpony-v1-sdxl",
            "John6666/god-pony-v2-sdxl",
            "John6666/urang-diffusion-v11-sdxl",
            "John6666/weakened-brs-pony-v1-sdxl",
            "John6666/2dfish-pony-animemix-v1-sdxl",
            "John6666/hadrian-delice-xl-v26j-sdxl",
            "John6666/3x3mix-xl-typeh-v1-sdxl",
            "John6666/rae-diffusion-xl-v2-sdxl-spo-pcm",
            "John6666/seishun-mix-v1-sdxl",
            "John6666/kurotsuki-mix-v1-sdxl",
            "John6666/wai-ani-hentai-pony-v2-sdxl",
            "John6666/wai-cute-v4-sdxl",
            "John6666/manmaru-mix-pony-v2-sdxl",
            "John6666/xl-colorful-dimension-v1-sdxl",
            "John6666/rae-diffusion-xl-v2-sdxl-spo-dpo-turbo",
            "John6666/flower-mix-cherry-xl-v4-sdxl",
            "John6666/cocoa-mix-xl-v5-25d-sdxl",
            "John6666/animix-v9-xl-animetvmix-v25-sdxl",
            "John6666/dreamland-base-28d-pony-v3-sdxl",
            "John6666/ohara-pdxl-v2-sdxl",
            "John6666/xlp-caulkinum-animeline-bnd-sdxl",
            "John6666/hassaku-xl-hentai-v13-better-eyes-sdxl",
            "John6666/xl-caulkinum-animeline-standard-bgm-sdxl",
            "John6666/xl-caulkinum-animeline-standard-aq-sdxl",
            "John6666/flyx3-mix-pony-xl-v1-sdxl",
            "John6666/fluffy-tart-xl-v15-sdxl",
            "John6666/grilled-lamprey-sdxl-v12o7n9745-sdxl",
            "John6666/ioli-pony-mix-v31-sdxl",
            "John6666/no-pony-beta01-v1-sdxl",
            "John6666/hentai-cinematic-pony-v2-sdxl",
            "John6666/cutiemagine-v1-sdxl",
            "John6666/new-tail-multiple-artists-v1-sdxl",
            "John6666/blafbastic-xl-v1-sdxl",
            "John6666/deep-dark-hentai-mix-v61hybrid-sdxl",
            "John6666/savant-v201-sdxl",
            "John6666/flyx3-mix-xl-v2-sdxl",
            "John6666/4th-tail-autism-v045-sdxl",
            "John6666/xl-merges-xl012rb2-sdxl",
            "John6666/akizone-style-xl-sdxl",
            "John6666/kntan-mix-xl-pony-v14-turbo-sdxl",
            "John6666/kntan-mix-xl-pony-v14-sdxl",
            "John6666/aaaautism-pony-finetune-aaaarestart-sdxl",
            "John6666/meinamix-meinav11-sd15",
            "John6666/mala-kawaii-pony-xl-v1-sdxl",
            "John6666/4th-tail-anime-hentai-v45-sdxl",
            "John6666/leekai-sdxl",
            "John6666/boleromix-pony-v141vae-sdxl",
            "John6666/perillaniumccm-pony-v1-sdxl",
            "John6666/hadrian-delice-xl-v25e-sdxl",
            "John6666/r-anime-3mil-testmodel-v1-sdxl",
            "John6666/mklan-anime-hentai-nextgen-darkhentai-v1-sdxl",
            "John6666/wai-ani-nsfw-ponyxl-v6-sdxl",
            "John6666/cute-candy-mix-pony-sdxl",
            "John6666/true-anime-style-pony-v2-sdxl",
            "John6666/pony-nai3-zycc-sdxl",
            "John6666/cicadaspony-v1-sdxl",
            "John6666/4gold-mixl-v111-sdxl",
            "John6666/copycat-bg-v1-sdxl",
            "John6666/lizmix-version-ex-sdxl",
            "John6666/asuma-xl-sdxl-spo-hyper",
            "John6666/asuma-xl-sdxl",
            "John6666/hotdog-pony-mix-xl-v4-sdxl",
            "John6666/ytpony3860xl-v09-sdxl",
            "John6666/model-ex-v5-sdxl",
            "John6666/ohara-pdxl-v1-sdxl",
            "John6666/rae-diffusion-xl-v2-sdxl-spo-hyper",
            "John6666/susamix-pony-v02-v1-for-animagine-sdxl",
            "John6666/1style-adjust-of-animaginexl31-v1-sdxl",
            "John6666/rain-pony-xl-rainfall-v2-sdxl",
            "John6666/aios-v101foal-v1100foalii-sdxl",
            "John6666/satan-pony-v2-sdxl",
            "John6666/pickled-pony-mix-v1-sdxl",
            "John6666/katayama-mix-xl-v1-sdxl",
            "John6666/megane-xl-v5-sdxl",
            "John6666/flyx3-mix-xl-v1-sdxl",
            "John6666/authaku-mix-v1-sdxl",
            "John6666/cocoa-mix-xl-v4-sdxl-spo",
            "John6666/shirataki-mix-xl-v1-sdxl-spo",
            "John6666/susamix-pony-v02-v1-sdxl-spo",
            "John6666/susamix-pony-v02-v1-sdxl",
            "John6666/wai-ani-hentai-pony-v1-sdxl",
            "John6666/sdxl-anime-illustration-v1-sdxl",
            "John6666/featureless-mix-pony-v2-sdxl-spo",
            "John6666/featureless-mix-pony-v2-sdxl",
            "John6666/raemu-xl-v4-sdxl-spo",
            "John6666/ely-pony-xl-v1-sdxl",
            "John6666/agenda-mix-pdxl-v15-sdxl",
            "John6666/toketap-v1-sdxl",
            "John6666/unreal-tulip-v1-sdxl",
            "John6666/hadrian-delice-xl-styled-stylea-v12d-sdxl",
            "John6666/bubble-style-xl-v1-sdxl",
            "John6666/crystal-clear-slime-nsf-v1-sdxl",
            "John6666/urang-diffusion-v1-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v5new-sdxl-spo",
            "John6666/mala-anime-mix-nsfw-pony-xl-v5new-sdxl",
            "John6666/bubble-xl-v1-sdxl",
            "John6666/cocoa-mix-xl-v4-sdxl",
            "John6666/wai-c-v3-sdxl",
            "John6666/atomix-pony-anime-xl-v3-sdxl",
            "John6666/hadrian-delice-xl-styled-stylea-v11h-sdxl",
            "John6666/flower-mix-moon-xl-v1-sdxl",
            "John6666/pony-pencil-xl-v2-sdxl",
            "John6666/pony-pencil-xl-v2-sdxl-spo",
            "John6666/ytpony3860xl-v1-sdxl",
            "John6666/celeste-pony-v2-sdxl",
            "John6666/eclipse-xl-v13test-sdxl",
            "John6666/ost-ander-mix-v1-sdxl",
            "John6666/sweet-mix-xl-v1-sdxl",
            "John6666/xl-merges-xl011-sdxl",
            "John6666/perfect-nai-v1-sdxl",
            "John6666/schizo-merges-arti-heart-neta-inception-sdxl",
            "John6666/cocoa-mix-xl-v3-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v5-sdxl-spo",
            "John6666/mala-anime-mix-nsfw-pony-xl-v5-sdxl",
            "John6666/3x3x3mixxl-v2-sdxl-spo",
            "John6666/3x3x3mixxl-v2-sdxl",
            "John6666/bnarhb-bright-night-and-ridiculously-huge-breasts-v1-sdxl",
            "John6666/cielx-v1-LCM-sdxl",
            "John6666/anime-screenshot-xl-v1-sdxl",
            "John6666/mikoshi-pony-v1-sdxl",
            "John6666/flower-mix-cherry-xl-v3-sdxl",
            "John6666/boring-cake-v1-sdxl",
            "John6666/schizo-merges-arti-heart-neta-v2-sdxl",
            "John6666/hadrian-delice-xl-styled-stylea-v10d-sdxl",
            "John6666/dissonance-v11-sdxl",
            "John6666/fpl005-sdxl",
            "John6666/bamboo-shoot-mix-v1-sdxl",
            "John6666/3d-rendering-style-beta2-sdxl",
            "John6666/wai-doll-cn-v2-sdxl",
            "John6666/asyncs-mix-pony-pony-v1-sdxl",
            "John6666/hamef-kawaii-mix-type24normal-warm-sdxl",
            "John6666/mala-smooth-v1-sdxl",
            "John6666/fluffy-tart-xl-v14-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v3-sdxl",
            "John6666/hamef-kawaii-mix-type24light-warm-sdxl",
            "John6666/ras-real-anime-screencap-v1-sdxl",
            "John6666/anima-pencil-xl-v5-sdxl-spo",
            "John6666/anima-pencil-xl-v5-sdxl",
            "John6666/randomizer89-pdxl-merge-v3-sdxl",
            "John6666/cocoa-mix-xl-v2-sdxl",
            "John6666/grilled-lamprey-sdxl-v10o4n3-sdxl",
            "John6666/white-unicorn-v2-sdxl-spo",
            "John6666/white-unicorn-v2-sdxl",
            "John6666/0002-pony-v31alt-sdxl",
            "John6666/rae-diffusion-xl-v2-sdxl-spo",
            "John6666/3x3mix-xl-typef-v1-sdxl",
            "John6666/horny-fox-v2-sdxl",
            "John6666/hoseki-lustrousmix-pony-v1-sdxl",
            "John6666/grilled-lamprey-sdxl-v10o1n9752-sdxl",
            "John6666/t-ponynai3-v55-sdxl-spo",
            "John6666/t-ponynai3-v55-sdxl",
            "John6666/0002-pony-v3-sdxl",
            "John6666/hassaku-xl-hentai-v12-sdxl",
            "John6666/sorkh-pony-v1-sdxl",
            "John6666/celeste-pony-v1-sdxl",
            "John6666/blue-pencil-xl-v7-sdxl-spo",
            "John6666/blue-pencil-xl-v7-sdxl",
            "John6666/counterfeit-xl-v25-sdxl-spo",
            "John6666/blue-pencil-xl-v6-sdxl-spo",
            "John6666/himawari-mix-xl-v13-sdxl-spo",
            "John6666/ioli-pony-mix-v2-sdxl-spo",
            "John6666/chacol-omega-mix-v11a-sdxl-spo",
            "John6666/hassaku-xl-hentai-v13-better-eyes-sdxl-spo",
            "John6666/ebara-pony-v1-sdxl-spo",
            "John6666/sympony-v2-fuga-sdxl",
            "John6666/cute-core-v1-sdxl",
            "John6666/animagine-xl-v31-sdxl-spo",
            "John6666/holodayo-xl-v21-sdxl-spo",
            "John6666/kivotos-xl-v20-sdxl-spo",
            "John6666/3x3x3mixxl-v1-sdxl-spo",
            "John6666/pvc-style-model-movable-pony-151-sdxl-spo",
            "John6666/t-ponynai3-v51wo-sdxl-spo",
            "John6666/anima-pencil-xl-v4-sdxl-spo",
            "John6666/pony-diffusion-v6-xl-sdxl-spo",
            "John6666/7th-anime-xl-pony-a-v1-sdxl-spo",
            "John6666/cocoa-mix-xl-v1-sdxl",
            "John6666/niji-style-xl-v21-sdxl",
            "John6666/animix-v9-xl-animetvmix-2nd-sdxl",
            "John6666/pegasusxx-v40-twilightsky-sdxl",
            "John6666/ebara-pony-v21-sdxl-spo",
            "John6666/ebara-pony-v21-sdxl-spo-lora",
            "John6666/kivotos-xl-v20-spo-lora",
            "John6666/pegana-merge-v2-sdxl",
            "John6666/getsujitsu-v1-sdxl",
            "John6666/flower-mix-cherry-xl-v2-sdxl",
            "John6666/tsuki-v2-sdxl",
            "John6666/xl-merges-xl010-sdxl",
            "John6666/bunny-mint-sdxl",
            "John6666/ebara-mfcg-pony-mix-v12-sdxl",
            "John6666/wai-cute-v3-sdxl",
            "John6666/equuleus-beta-pony-mix-v1-sdxl",
            "John6666/3x3mix-xl-typea-v2-sdxl",
            "John6666/ioli-pony-mix-v2-sdxl",
            "John6666/sagittarius-beta-pony-mix-v1-sdxl",
            "John6666/hamef-kawaii-mix-type2light-sdxl",
            "John6666/aniease-v24-sdxl",
            "John6666/sol-pony-v2-alt-sdxl",
            "John6666/eva-claus-mix-pony-xl-v21-sdxl",
            "John6666/0003-pony-delta-sdxl",
            "John6666/rae-diffusion-xl-v1-sdxl",
            "John6666/persona-style-checkpoint-pony-xl-sdxl",
            "John6666/sympony-v1-prelude-sdxl",
            "John6666/himawari-mix-xl-v13-sdxl",
            "John6666/3x3mix-xl-typee-v1-sdxl",
            "John6666/r-anime-220k-v1-sdxl",
            "John6666/comradeship-xl-v9a-spo-dpo-flash-sdxl",
            "John6666/hassaku-xl-hentai-v13-sdxl",
            "John6666/knk-soft-shading-v1-sdxl",
            "John6666/astolfo-mix-xl-tgmd-sdxl",
            "John6666/nova-anime-xl-pony-v2-sdxl",
            "John6666/hadrian-delice-xl-v20l-sdxl",
            "John6666/confusion-xl-v3-sdxl",
            "John6666/luminastra-xl-v2-sdxl",
            "John6666/featureless-25d-mix-pony-v1-sdxl",
            "John6666/ebara-mfcg-pony-mix-v11-sdxl",
            "John6666/nero-mix-v1-sdxl",
            "John6666/ebara-pony-v21-sdxl-fp32",
            "John6666/ebara-pony-v21-sdxl",
            "John6666/mala-anime-mix-nsfw-pony-xl-v4-sdxl",
            "John6666/3x3mix-xl-typed-v1-sdxl",
            "John6666/kosa-v2-sdxl",
            "John6666/pegana-merge-v1-sdxl",
            "John6666/kohaku-xl-epsilon-rev2-sdxl",
            "John6666/99mix-v1-sdxl",
            "John6666/hentai-cinematic-pony-v1-sdxl",
            "John6666/pegasusxx-v383-sdxl",
            "John6666/pony-pencil-sdxl",
            "John6666/sino-station-xl-manhua-v8-sdxl",
            "John6666/wai-ani-nsfw-ponyxl-v5-sdxl",
            "John6666/boleromix-pony-v14-sdxl",
            "John6666/pegasusxx-v35-sdxl",
            "John6666/eclipse-xl-v1-sdxl",
            "John6666/kome-anime-coloring-chibi-style-v1-sdxl",
            "John6666/base-anime-style-pony-v3-sdxl",
            "John6666/t-ponynai3-v51-sdxl",
            "John6666/copycat-v2-sdxl",
            "John6666/asyncs-mix-xl-v31-sdxl",
            "John6666/adamah-mix-xl-v15-sdxl",
            "John6666/ponymagine-v91-gamma-sdxl",
            "John6666/super-robot-diffusion-rise-v1-sdxl",
            "John6666/animix-v9-xl-sdxl",
            "John6666/pthno2-v1-sdxl",
            "John6666/xl-caulkinum-animeline-gd-sdxl",
            "John6666/xl-caulkinum-animeline-gep-sdxl",
            "John6666/sino-station-xl-ponyart-sdxl",
            "John6666/eva-claus-mix-pony-xl-v1-sdxl",
            "John6666/wai-cute-v2-sdxl",
            "John6666/real-pony-real-anime-v4-sdxl",
            "John6666/osorubeshi-xl-nsfw-hyper-v1-sdxl",
            "John6666/comradeship-xl-v9-sdxl",
            "John6666/heart-of-apple-xl-v3-sdxl",
            "John6666/tri-fusion-v1e-sdxl",
            "John6666/himawari-mix-xl-v6-sdxl",
            "John6666/nsfw-anime-xl-v1-sdxl",
            "John6666/aniease-v23-sdxl",
            "John6666/any-orange-mix-xl-v1-sdxl",
            "John6666/white-unicorn-another-sdxl",
            "John6666/pony-pencil-xl-v102-sdxl",
            "John6666/anime-illust-diffusion-v8-sdxl",
            "John6666/neta-art-xl-v1dpo-sdxl",
            "John6666/raemu-xl-v35l-sdxl",
            "John6666/aing-diffusion-xl-v13-sdxl",
            "John6666/prefect-pony-xl-v1-sdxl",
            "John6666/omega-pony-anime-style-v2-sdxl",
            "John6666/stuffy-mix-v1-sdxl",
            "John6666/chacol-omega-mix-v11a-sdxl",
            "John6666/epona-mix-v3-sdxl",
            "John6666/manmaru_mix_pony-v1-sdxl",
            "John6666/featureless-mix-pony-v1-sdxl",
            "John6666/baxl-v3-sdxl",
            "John6666/cute-core-v3-sdxl",
            "John6666/yamers-anime-sa-sdxl",
            "John6666/3x3x3mixxl-v1-sdxl",
            "John6666/momoiro-pony-v14-sdxl",
            "John6666/hanamomo-pony-v14-sdxl",
            "John6666/anime-bulldozer-v2-sdxl",
            "John6666/deep-dark-hentai-mix-v60-sdxl",
            "John6666/ebara-pony-v1-sdxl",
            "John6666/anima-pencil-sdxl",
            "John6666/truetolife-sdxl-xxx-v13-sdxl",
            "John6666/voluptuous-mix-ponyxl-v11-sdxl",
            "John6666/promissing-bareskin-xl-v6-sdxl",
            "John6666/acolyte-sdxl-v1-sdxl",
            "John6666/bd-pony-real-v01h-sdxl",
            "John6666/iniverse-is-boning-v11-sdxl",
            "John6666/damn-ponyxl-realistic-model-v3-sdxl",
            "John6666/eternal-champon-a-v1-sdxl",
            "John6666/duchaiten-pony-real-v11fix-sdxl",
            "John6666/catgen-sdxl-fine-tune-v1-sdxl",
            "John6666/sevenof9-pony-real-mix-smartevolution-contrast-sdxl",
            "John6666/the-araminta-ev4-sdxl",
            "John6666/pinkiepie-pony-mix-v35alt-sdxl",
            "John6666/titania-noah-mix-25d27d-v50-sdxl",
            "John6666/wai-semireal-v1-sdxl",
            "John6666/vendo-pony-realistic-v13lora-sdxl",
            "John6666/stoiqo-new-reality-sdxl-xlpro-sdxl",
            "John6666/titania-mix-realistic-pony-gbvr10-sdxl",
            "John6666/serendipity-pdxl-v2-sdxl",
            "John6666/natvis-natural-vision-v1-sdxl",
            "John6666/iniverse-is-boning-v1-sdxl",
            "John6666/safetensors_converting_test",
            "John6666/satpony-no-score-v3-sdxl",
            "John6666/foxai-x-duchaiten-v1-sdxl",
            "John6666/kaguya-v395-sdxl",
            "John6666/titania-mix-realistic-pony-gbv90-sdxl",
            "John6666/badbro-xl-v8-sdxl",
            "John6666/raelestia-xl-v2-sdxl",
            "John6666/only-porn-sdxl-pony-sdxl",
            "John6666/precum-xl-v1-sdxl",
            "John6666/ls-equost-real-xl-aev1-sdxl",
            "John6666/donuts-delivery-mix-v1-sdxl",
            "John6666/cyberrealistic-pony-v61-sdxl",
            "John6666/mangled-merge-xl-magic-sdxl",
            "John6666/cognitive-river-v2-sdxl",
            "John6666/rdxl-smash-bros-pony1-sdxl",
            "John6666/asian-orchid-blossom-beauty-and-golden-silk-v1-sdxl",
            "John6666/uncanny-valley-v2-sdxl",
            "John6666/eldritch-photography-eldritch-merge-sdxl",
            "John6666/3010nc-xx-mixpony-v26-sdxl",
            "John6666/satpony-v3-realism-sdxl",
            "John6666/zaxious-xl-wildchild30-sdxl",
            "John6666/roar-realm-of-awesome-realism-v30-sdxl",
            "John6666/fennfoto-pony-v3-sdxl",
            "John6666/3x3mix-xl-typel-v1-sdxl",
            "John6666/dagny-pony-half-xl-sdxl",
            "John6666/ida-pony-half-xl-sdxl",
            "John6666/duchesses-of-worcester-v1-sdxl",
            "John6666/halcyon-sdxl-photorealism-v18-sdxl",
            "John6666/truetolife-sdxl-xxx-v12-sdxl",
            "John6666/aimz-dream-real-pony-mix-v3-sdxl",
            "John6666/godiva-v3-sdxl",
            "John6666/sborka-random-v30xl-sdxl",
            "John6666/gdp-pony-xl-v11-sdxl",
            "John6666/creaprompt-ultimate6-sdxl",
            "John6666/photoart-v1-sdxl",
            "John6666/icarus-mix-sdxl-v1-sdxl",
            "John6666/pony-photo-real-merge-x3-v2sharper-sdxl",
            "John6666/cyberrealistic-pony-v6-sdxl",
            "John6666/the-araminta-ev3-sdxl",
            "John6666/magica-pony-realism-dark-magica-sdxl",
            "John6666/jib-mix-realistic-xl-v14-crystal-clarity-sdxl",
            "John6666/serendipity-pdxl-darkfantasy-sdxl",
            "John6666/sevenof9-pony-real-mix-smartevolution-sdxl",
            "John6666/cinero-pony-nsfw-v09d-sdxl",
            "John6666/indecent-v1-sdxl",
            "John6666/cinero-pony-nsfw-v09a-sdxl",
            "John6666/lyuyang-mix-v304-sdxl",
            "John6666/devlish-photo-realism-sdxl-v16-sdxl",
            "John6666/meichidark-mix-meichidarkanimxlv1-sdxl",
            "John6666/wai-10step-hyper-no-score-realistic-pony-xl-v1-sdxl",
            "John6666/cyberrealistic-pony-v5-sdxl",
            "John6666/goth-chix-mix-v1-sdxl",
            "John6666/3010nc-xx-mixpony-v25-sdxl",
            "John6666/kaguya-v22-sdxl",
            "John6666/satpony-journey-v1-sdxl",
            "John6666/real-dream-sdxlpony9-sdxl",
            "John6666/wai-nature-real-mix-v1-sdxl",
            "John6666/godiva-v2-sdxl",
            "John6666/pinkiepie-pony-mix-v34-sdxl",
            "John6666/iris-lux-polyvalent-prototype-v1051-sdxl",
            "John6666/stoiqo-afrodite-xl-xl31-sdxl",
            "John6666/mbh-reality-plus-v2-sdxl",
            "John6666/marusube-realistic-v1-sdxl",
            "John6666/titania-mix-realistic-pony-gbv80-sdxl",
            "John6666/stoiqo-raffaello-xl-xl2-sdxl",
            "John6666/stoiqo-newreality-sdxl-xl4-sdxl",
            "John6666/batch-co-pony-v1-sdxl",
            "John6666/wai-real-cn-v8-sdxl",
            "John6666/am-i-real-v45-sd15",
            "John6666/dream-pony-v83-sdxl",
            "John6666/getphat-pony-lewdfusion-v1-sdxl",
            "John6666/osorubeshi-pony-real-v7-sdxl",
            "John6666/titania-juggernaut-mix-v1-sdxl",
            "John6666/sevenof9-pony-real-mix-nextgen-sdxl",
            "John6666/pony-photo-real-merge-x3-v1-sdxl",
            "John6666/tsubaki-mix-v15-sdxl",
            "John6666/wai-real-e-v1-sdxl",
            "John6666/epicrealism-xl-v8kiss-sdxl",
            "John6666/lilith-pony-realmix-v1-sdxl",
            "John6666/badbro-xl-v5-sdxl",
            "John6666/gurila-mash-xxx-sdxl-v1-sdxl",
            "John6666/anteros-xxxl-v1-sdxl",
            "John6666/big-lust-v1-sdxl",
            "John6666/ecstacy-pony-v19-photoreal-sdxl",
            "John6666/lustify-sdxl-nsfwsfw-v1-sdxl",
            "John6666/vendo-pony-realistic-v12-sdxl",
            "John6666/kaguya-v1-sdxl",
            "John6666/zonkey-realism-v5-sdxl",
            "John6666/real-mix-pony-v4-sdxl",
            "John6666/datass-rev-final-pony-realism-final-sdxl",
            "John6666/colorful-xl-v7-sdxl",
            "John6666/pony-asian-realism-alpha-v05-sdxl",
            "John6666/ultimate-realistic-mix-v2-sdxl",
            "John6666/titania-mix-realistic-pony-gbv70-sdxl",
            "John6666/3010nc-xx-mixpony-v21-sdxl",
            "John6666/big-asp-v1-sdxl",
            "John6666/titania-mix-realistic-pony-gbv60-sdxl",
            "John6666/pinkiepie-pony-mix-v32-sdxl",
            "John6666/iniverse-mix-xl-sfwnsfw-pony-v11-xl-lora-comp-sdxl",
            "John6666/swam-pony-xl-v2-sdxl",
            "John6666/speciosa-25d-v12-sdxl",
            "John6666/3010nc-xx-mixpony-v20-sdxl",
            "John6666/chacol-semi-real-pony-mix-xl-v1-sdxl",
            "John6666/3x3mix-xl-typeg-v1-sdxl",
            "John6666/barry-the-quokka-sdxl-lora",
            "John6666/wai-real-cn-v7-sdxl",
            "John6666/speciosa-25d-v11a-sdxl",
            "John6666/badbro-xl-v3-sdxl",
            "John6666/ultimate-realistic-mix-v1-sdxl",
            "John6666/cookie-run-character-style-v1-sd15-lora",
            "John6666/colorful-realistic-xl-v1-sdxl",
            "John6666/titania-mix-realistic-pony-gbv50-sdxl",
            "John6666/speciosa-v12-sdxl",
            "John6666/3010nc-xx-mixpony-v17-sdxl",
            "John6666/aimz-dream-real-pony-mix-v2-sdxl",
            "John6666/osorubeshi-pony-real-v6c-sdxl",
            "John6666/juggernaut-reborn-sd15",
            "John6666/realistic-vision-v60-b1-sd15",
            "John6666/forreal-xl-v5-sdxl",
            "John6666/real-vis-xl-v40-sdxl",
            "John6666/iniverse-mix-xl-sfwnsfw-pony-beta-v10-sdxl",
            "John6666/duchaiten-pony-real-v1-sdxl",
            "John6666/fennfoto-pony-v2-sdxl",
            "John6666/titania-mix-realistic-pony-gbv40-sdxl",
            "John6666/3010nc-xx-mixpony-v16-sdxl",
            "John6666/real-mix-pony-v3-sdxl",
            "John6666/3010nc-xx-mixpony-v15-sdxl",
            "John6666/local_gokaygokay_Florence-2-SD3-Captioner_Tagger",
            "John6666/hpony-realism-25d-v20real-sdxl",
            "John6666/iniverse-mix-xl-sfwnsfw-guofen-v15-sdxl",
            "John6666/titania-mix-realistic-pony-gbv30-sdxl",
            "John6666/wai-simpleuse-for-real-pony-v1-sdxl",
            "John6666/digital-af-xlp-v1-sdxl",
            "John6666/wai-real-mix-v8-sdxl-spo",
            "John6666/wai-real-mix-v8-sdxl",
            "John6666/real-mix-pony-v2-sdxl",
            "John6666/mklan-realistic-pony-nextgen-ponyv1-sdxl",
            "John6666/firexxx-realistic-nsfw-v1-sdxl",
            "John6666/titania-mix-realistic-pony-gbv20-sdxl",
            "John6666/titania-mix-realistic-pony-gbv10-sdxl",
            "John6666/gokaygokay-Florence-2-SD3-Captioner-8bit",
            "John6666/jib-mix-pony-realistic-v2-sdxl",
            "John6666/duchaiten-pony-real-beta8-sdxl",
            "John6666/wai-real-mix-v7-sdxl-spo",
            "John6666/wai-real-cn-v6-sdxl-spo",
            "John6666/swam-pony-xl-v1-sdxl",
            "John6666/maple-mix-pony-v1-sdxl-spo-lora",
            "John6666/pinkiepie-pony-mix-v30beta-sdxl",
            "John6666/jac-nsfw-v2f-sdxl",
            "John6666/lyuyang-mix-vp-v198-sdxl",
            "John6666/wai-real-cn-v6-sdxl",
            "John6666/pony-realism-v21main-sdxl",
            "John6666/llama-tagger-HF-GPTQ-4bits",
            "John6666/maple-mix-pony-v1-sdxl",
            "John6666/jac-nsfw-v1f-sdxl",
            "John6666/duchaiten-pony-real-beta4-sdxl",
            "John6666/wai-real-cn-v5-sdxl",
            "John6666/wai-real-cn-v4-sdxl",
            "John6666/sexoholic-real-pony-nsfw-v2-sdxl",
            "John6666/photo-realistic-pony-v5-sdxl",
            "John6666/mist-xl-hyper-character-style-model-sdxl",
            "John6666/duchaiten-pony-real-alpha7-sdxl",
            "John6666/9527-detail-realistic-xl-v55mix-sdxl",
            "John6666/runbullxl-v8-sdxl",
            "John6666/yaminabe-pony-v6-sdxl",
            "John6666/deng-pvc-xl-mix2-v1-sdxl",
            "John6666/better-than-hentai-xxxl-unreal-pony-mk2-sdxl",
            "John6666/schedulars_test",
            "John6666/real-mix-pony-v01-sdxl",
            "John6666/duchaiten-pony-real-alpha5-sdxl",
            "John6666/osorubeshi-pony-real-x-sdxl",
            "John6666/cosmix-v2-sdxl",
            "John6666/xl-caulkinum-realline-sj-sdxl",
            "John6666/juggernaut-xl-rundiffusion-hyper-sdxl",
            "John6666/after-real-xl-beta2-sdxl",
            "John6666/cherry-picker-xl-v3-sdxl",
            "John6666/fuduki-mix-v2-sdxl",
            "John6666/real-pony-cutejp-v3-sdxl",
            "John6666/rumblexl-v13-sdxl",
          ],
        },
        unknownParam: {
          type: "unknown",
          value: "",
          hide: true,
        },
        unknownParamNum1: {
          type: "unknown",
          value: 1,
          hide: true,
        },
        unknownParam2: {
          type: "unknown",
          value: "",
          hide: true,
        },
        unknownParamNum2: {
          type: "unknown",
          value: 1,
          hide: true,
        },
        unknownParam3: {
          type: "unknown",
          value: "",
          hide: true,
        },
        unknownParamNum3: {
          type: "unknown",
          value: 1,
          hide: true,
        },
        unknownParam4: {
          type: "unknown",
          value: "",
          hide: true,
        },
        unknownParamNum4: {
          type: "unknown",
          value: 1,
          hide: true,
        },
        unknownParam5: {
          type: "unknown",
          value: "",
          hide: true,
        },
        unknownParamNum5: {
          type: "unknown",
          value: 1,
          hide: true,
        },
        sampler: {
          isAdvanceoption: true,
          value: "Euler a",
          type: "dropdown",
          options: [
            "DPM++ 2M",
            "DPM++ 2M Karras",
            "DPM++ 2M SDE",
            "DPM++ 2M SDE Karras",
            "DPM++ 2S",
            "DPM++ 2S Karras",
            "DPM++ 1S",
            "DPM++ 1S Karras",
            "DPM++ 3M",
            "DPM++ 3M Karras",
            "DPM++ SDE",
            "DPM++ SDE Karras",
            "DPM2",
            "DPM2 Karras",
            "DPM2 a",
            "DPM2 a Karras",
            "Euler",
            "Euler a",
            "Euler trailing",
            "Euler a trailing",
            "Heun",
            "Heun Karras",
            "LMS",
            "LMS Karras",
            "DDIM",
            "DDIM trailing",
            "DEIS",
            "UniPC",
            "UniPC Karras",
            "PNDM",
            "Euler EDM",
            "Euler EDM Karras",
            "DPM++ 2M EDM",
            "DPM++ 2M EDM Karras",
            "DDPM",
            "DPM++ 2M Lu",
            "DPM++ 2M Ef",
            "DPM++ 2M SDE Lu",
            "DPM++ 2M SDE Ef",
            "LCM",
            "TCD",
            "LCM trailing",
            "TCD trailing",
            "LCM Auto-Loader",
            "TCD Auto-Loader",
          ],
        },
        unknownParamfinal: {
          type: "unknown",
          value: "none",
          hide: true,
        },
      },
    },
  },
};

const FormPayloadSlice = createSlice({
  name: "FormPayload",
  initialState,
  reducers: {
    setElements: (state, action) => {
      state.formPayload = action.payload;
    },
  },
});

export const { setElements } = FormPayloadSlice.actions;

// export const selectFormPayload = (state) => state.FormPayload;

export default FormPayloadSlice.reducer;
