import { createSlice } from "@reduxjs/toolkit";

// const type payloadProp = {
//   formPayload : {
//     [key]:{
//       payload:{
//         [key]:{
//           isRequired:Boolean,
//           value:string | number,
//           type:string,
//           options:string[],
//           isAdvanceoption:Boolean,
//           hide:Boolean,
//           min:number,
//           max:number,
//           isFloat:boolean
//           isRandomizefn:fn
//         }
//       }
//     }
//   }
// }
const initialState = {
  formPayload: {
    "prithivMLmods/IMAGINEO-4K": {
      payloadType: "string", // if withKeys then use prompt as it is
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          isAdvanceoption: true,
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        collage_style: {
          value: "Hi-Res",
          type: "radio",
          options: [
            "Hi-Res",
            "B & W",
            "Polaroid",
            "Watercolor",
            "Cinematic",
            "Nostalgic",
            "Vintage",
            "Scrapbook",
            "NeoNGlow",
            "Geometric",
            "Thematic",
            "Cherry",
            "Fuchsia",
            "Pop",
            "Violet",
            "Sea Blue",
            "Sea Green",
            "Mustard",
            "Amber",
            "Pomelo",
            "Peppermint",
            "Mystic",
            "Pastel",
            "Coral",
            "No Style",
          ],
        }, //choices
        filter_name: {
          value: "Zero filter",
          type: "radio",
          options: [
            "Vivid",
            "Playa",
            "Desert",
            "West",
            "Blush",
            "Minimalist",
            "Zero filter",
          ],
        },
        grid_size: {
          value: "1x1",
          type: "dropdown",
          options: ["1x1", "2x1", "1x2", "2x2", "2x3", "3x2", "3x3"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "mukaist/Midjourney": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          isAdvanceoption: true,
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "mukaist/DALLE-4K": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value:
            "(deformed iris, deformed pupils), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        style: {
          isAdvanceoption: true,
          value: "3840 x 2160",
          type: "radio",
          options: ["3840 x 2160", "2560 x 1440", "HD+", "Style Zero"],
        },
        seed: { isAdvanceoption: true, value: 0, type: "number" },
        width: { isAdvanceoption: true, value: 512, type: "number" },
        height: { isAdvanceoption: true, value: 512, type: "number" },
        guidance_scale: { isAdvanceoption: true, value: 1, type: "number" },
        randomize_seed: {
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "Boboiazumi/animagine-xl-3.1": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
          // label:""
          // desc:""
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        seed: {
          isAdvanceoption: true,
          value: Math.floor(Math.random() * (2147483647 + 1)),
          type: "number",
          isRandomize: true,
        },
        custom_width: {
          isAdvanceoption: true,
          value: 1024,
          type: "number",
          min: 512,
          max: 2048,
        },
        custom_height: {
          isAdvanceoption: true,
          value: 1024,
          type: "number",
          min: 512,
          max: 2048,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 7,
          type: "slider",
          min: 1,
          max: 12,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 28,
          type: "slider",
          min: 1,
          max: 50,
        },
        sampler: {
          value: "Euler a",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Karras",
            "Euler",
            "Euler a",
            "DDIM",
          ],
        },
        aspect_ratio_selector: {
          value: "896 x 1152",
          options: [
            "1024 x 1024",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
        style_selector: {
          value: "(None)",
          type: "radio",
          options: [
            "(None)",
            "Cinematic",
            "Photographic",
            "Anime",
            "Manga",
            "Digital Art",
            "Pixel art",
            "Fantasy art",
            "Neonpunk",
            "3D Model",
          ],
        },
        quality_selector: {
          type: "dropdown",
          value: "Standard v3.1",
          options: [
            "(None)",
            "Standard v3.0",
            "Standard v3.1",
            "Light v3.1",
            "Heavy v3.1",
          ],
        },
        use_upscaler: { type: "checkbox", value: false }, // boolean  in 'Use Upscaler' Checkbox component
        upscaler_strength: {
          type: "slider",
          value: 0.5,
          hide: true,
          min: 0,
          max: 1,
          step: 0.1,
          isFloat: true,
        }, // image strength
        upscale_by: {
          type: "slider",
          value: 1,
          min: 1,
          max: 1.5,
          step: 0.1,
          isFloat: true,
        },
        add_quality_tags: {
          type: "checkbox",
          value: true,
        },
        isImg2Img: {
          type: "checkbox",
          value: false,
          hide: true,
        },
        img_path: {
          type: "imageUpload",
          hide: true,
          value: null,
        },
        img2img_strength: {
          value: 0.5,
          type: "slider",
          min: 0,
          max: 1,
          hide: true,
        },
      },
    },
    "prodia/sdxl-stable-diffusion-xl": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "(deformed eyes, nose, ears, nose), bad anatomy, ugly",
          type: "textarea",
        },
        stable_diffusion_checkpoints: {
          value: "sd_xl_base_1.0.safetensors [be9edd61]",
          type: "dropdown",
          options: [
            "animagineXLV3_v30.safetensors [75f2f05b]",
            "devlishphotorealism_sdxl15.safetensors [77cba69f]",
            "dreamshaperXL10_alpha2.safetensors [c8afe2ef]",
            "dynavisionXL_0411.safetensors [c39cc051]",
            "juggernautXL_v45.safetensors [e75f5471]",
            "realismEngineSDXL_v10.safetensors [af771c3f]",
            "realvisxlV40.safetensors [f7fdcb51]",
            "sd_xl_base_1.0.safetensors [be9edd61]",
            "sd_xl_base_1.0_inpainting_0.1.safetensors [5679a81a]",
            "turbovisionXL_v431.safetensors [78890989]",
          ],
        },
        sampling_step: {
          value: 20,
          type: "slider",
          isAdvanceoption: true,
          min: 1,
          max: 25,
        },
        sampler: {
          isAdvanceoption: true,
          value: "DPM++ 2M Karras",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Exponential",
            "DPM++ 2M SDE Karras",
            "Euler a",
            "Euler",
            "LMS",
            "Heun",
            "DPM2",
            "DPM2 a",
            "DPM++ 2S a",
            "DPM++ 2M",
            "DPM++ SDE",
            "DPM++ 2M SDE",
            "DPM++ 2M SDE Heun",
            "DPM++ 2M SDE Heun Karras",
            "DPM++ 2M SDE Heun Exponential",
            "DPM++ 3M SDE",
            "DPM++ 3M SDE Karras",
            "DPM++ 3M SDE Exponential",
            "DPM fast",
            "DPM adaptive",
            "LMS Karras",
            "DPM2 Karras",
            "DPM2 a Karras",
            "DPM++ 2S a Karras",
            "Restart",
            "DDIM",
            "PLMS",
          ],
        },
        cfg_scale: {
          value: 7,
          type: "slider",
          isAdvanceoption: true,
          min: 1,
          max: 20,
        },
        width: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        height: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 1536,
        },
        seed: {
          type: "number",
          isAdvanceoption: true,
          value: -1,
        },
      },
    },
    "KingNish/SDXL-Flash": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        use_negative_prompt: {
          value: true,
          type: "checkbox",
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 3,
          type: "slider",
          step: 0.1,
          min: 0.1,
          max: 6,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 8,
          type: "slider",
          min: 1,
          max: 15,
        },
        randomize_seed: {
          hide: true,
          isAdvanceoption: true,
          value: true,
          type: "checkbox",
        },
      },
    },
    "Akimitsujiro/Stable-Diffusion-XL": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          isAdvanceoption: true,
          value: 512,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          isAdvanceoption: true,
          value: 512,
          type: "slider",
          min: 512,
          max: 4096,
        },
        guidance_scale: {
          isAdvanceoption: true,
          value: 7,
          type: "slider",
          step: 0.1,
          min: 0.1,
          max: 12,
        },
        num_inference_steps: {
          isAdvanceoption: true,
          value: 28,
          type: "slider",
          min: 1,
          max: 50,
        },
        sampler: {
          isAdvanceoption: true,
          value: "Euler a",
          type: "dropdown",
          options: [
            "DPM++ 2M Karras",
            "DPM++ SDE Karras",
            "DPM++ 2M SDE Karras",
            "Euler",
            "Euler a",
            "DDIM",
            "DPM++ 2S a",
            "Heun",
            "DPM fast",
          ],
        },
        aspect_ratio_selector: {
          isAdvanceoption: true,
          value: "896 x 1152",
          options: [
            "1024 x 1024",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
        collage_style: {
          value: "(None)",
          type: "radio",
          options: [
            "(None)",
            "Cinematic",
            "Photographic",
            "Anime",
            "Manga",
            "Digital Art",
            "Pixel art",
            "Fantasy art",
            "Neonpunk",
            "3D Model",
            "Analog Film",
            "Comics Book",
            "Line Art",
            "Illustration | Anime",
            "Illustration | Chibi",
            "Design | Avatar",
            "Glitch",
            "Pencil",
            "Texture",
            "Advertising",
            "Food Photography",
            "Real Estate",
            "Abstract",
            "Cubist",
            "Graffiti",
            "Hyperrealism",
            "Impressionist",
            "Pointillism",
            "Pop Art",
            "Psychedelic",
            "Renaissance",
            "Steampunk",
            "Surrealist",
            "Typography",
            "Watercolor",
            "Fighting Game",
            "GTA",
            "Super Mario",
            "Minecraft",
            "Pokémon",
            "Retro Arcade",
            "Retro Game",
            "RPG Fantasy Game",
            "Strategy Game",
            "Street Fighter",
            "Legend of Zelda",
            "Architectural",
            "Disco",
            "Dreamscape",
            "Dystopian",
            "Fairy Tale",
            "Gothic",
            "Grunge",
            "Horror",
            "Minimalist",
            "Monochrome",
            "Nautical",
            "Space",
            "Stained Glass",
            "Techwear Fashion",
            "Tribal",
            "Zentangle",
            "Collage",
            "Flat Papercut",
            "Kirigami",
            "Paper Mache",
            "Paper Quilling",
            "Papercut Collage",
            "Papercut Shadow Box",
            "Stacked Papercut",
            "Thick Layered Papercut",
            "Alien",
            "Film Noir",
            "HDR",
            "Long Exposure",
            "Neon Noir",
            "Silhouette",
            "Tilt-Shift",
          ],
        },
        quality_selector: {
          type: "dropdown",
          value: "Standard v3.1",
          options: [
            "(None)",
            "Standard v3.0",
            "Standard v3.1",
            "Light v3.1",
            "Heavy v3.1",
            "NSFW",
          ],
        },
        use_upscaler: { type: "checkbox", value: false }, // boolean  in 'Use Upscaler' Checkbox component
        upscaler_strength: {
          type: "slider",
          value: 0.5,
          // hide: true,
          min: 0,
          max: 1,
          step: 0.5,
          isFloat: true,
        },
        upscale_by: {
          type: "slider",
          value: 1,
          min: 1,
          max: 1.5,
          step: 0.1,
          isFloat: true,
        },
        add_quality_tags: {
          type: "checkbox",
          value: true,
        },
      },
    },
    "prithivMLmods/EPIC-REALISM": {
      payloadType: "string",
      payload: {
        prompt: {
          isRequired: true,
          value: "",
          type: "text",
        },
        negative_prompt: {
          value: "",
          type: "textarea",
        },
        unknownParam: {
          type: "unknown",
          value: true,
          hide: true,
        },
        seed: {
          isAdvanceoption: true,
          value: 0,
          type: "number",
          isRandomize: true,
          hide: true,
        },
        width: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        height: {
          isAdvanceoption: true,
          value: 1024,
          type: "slider",
          min: 512,
          max: 4096,
        },
        unknownParam2: {
          type: "unknown",
          value: 3,
          hide: true,
        },
        unknownParam3: {
          type: "unknown",
          value: true,
          hide: true,
        },
        aspect_ratio_selector: {
          value: "3840 x 2160",
          hide: true,
          options: [
            "3840 x 2160",
            "1152 x 896",
            "896 x 1152",
            "1216 x 832",
            "832 x 1216",
            "1344 x 768",
            "768 x 1344",
            "1536 x 640",
            "640 x 1536",
            "Custom",
          ],
          type: "radio",
        },
      },
    },
    // "prodia/fast-stable-diffusion": {
    //   payloadType: "string",
    //   payload: {
    //     prompt: {
    //       isRequired: true,
    //       value: "",
    //       type: "text",
    //     },
    //     negative_prompt: {
    //       value: "",
    //       type: "textarea",
    //     },
    //     stable_diffusion_checkpoints: {
    //       value: "absolutereality_v181.safetensors [3d9d4d2b]",
    //       type: "dropdown",
    //       options: [
    //         "3Guofeng3_v34.safetensors [50f420de]",
    //         "absolutereality_V16.safetensors [37db0fc3]",
    //         "absolutereality_v181.safetensors [3d9d4d2b]",
    //         "amIReal_V41.safetensors [0a8a2e61]",
    //         "analog-diffusion-1.0.ckpt [9ca13f02]",
    //         "aniverse_v30.safetensors [579e6f85]",
    //         "anythingv3_0-pruned.ckpt [2700c435]",
    //         "anything-v4.5-pruned.ckpt [65745d25]",
    //         "anythingV5_PrtRE.safetensors [893e49b9]",
    //         "AOM3A3_orangemixs.safetensors [9600da17]",
    //         "blazing_drive_v10g.safetensors [ca1c1eab]",
    //         "breakdomain_I2428.safetensors [43cc7d2f]",
    //         "breakdomain_M2150.safetensors [15f7afca]",
    //         "cetusMix_Version35.safetensors [de2f2560]",
    //         "childrensStories_v13D.safetensors [9dfaabcb]",
    //         "childrensStories_v1SemiReal.safetensors [a1c56dbb]",
    //         "childrensStories_v1ToonAnime.safetensors [2ec7b88b]",
    //         "Counterfeit_v30.safetensors [9e2a8f19]",
    //         "cuteyukimixAdorable_midchapter3.safetensors [04bdffe6]",
    //         "cyberrealistic_v33.safetensors [82b0d085]",
    //         "dalcefo_v4.safetensors [425952fe]",
    //         "deliberate_v2.safetensors [10ec4b29]",
    //         "deliberate_v3.safetensors [afd9d2d4]",
    //         "dreamlike-anime-1.0.safetensors [4520e090]",
    //         "dreamlike-diffusion-1.0.safetensors [5c9fd6e0]",
    //         "dreamlike-photoreal-2.0.safetensors [fdcf65e7]",
    //         "dreamshaper_6BakedVae.safetensors [114c8abb]",
    //         "dreamshaper_7.safetensors [5cf5ae06]",
    //         "dreamshaper_8.safetensors [9d40847d]",
    //         "edgeOfRealism_eorV20.safetensors [3ed5de15]",
    //         "EimisAnimeDiffusion_V1.ckpt [4f828a15]",
    //         "elldreths-vivid-mix.safetensors [342d9d26]",
    //         "epicphotogasm_xPlusPlus.safetensors [1a8f6d35]",
    //         "epicrealism_naturalSinRC1VAE.safetensors [90a4c676]",
    //         "epicrealism_pureEvolutionV3.safetensors [42c8440c]",
    //         "ICantBelieveItsNotPhotography_seco.safetensors [4e7a3dfd]",
    //         "indigoFurryMix_v75Hybrid.safetensors [91208cbb]",
    //         "juggernaut_aftermath.safetensors [5e20c455]",
    //         "lofi_v4.safetensors [ccc204d6]",
    //         "lyriel_v16.safetensors [68fceea2]",
    //         "majicmixRealistic_v4.safetensors [29d0de58]",
    //         "mechamix_v10.safetensors [ee685731]",
    //         "meinamix_meinaV9.safetensors [2ec66ab0]",
    //         "meinamix_meinaV11.safetensors [b56ce717]",
    //         "neverendingDream_v122.safetensors [f964ceeb]",
    //         "openjourney_V4.ckpt [ca2f377f]",
    //         "pastelMixStylizedAnime_pruned_fp16.safetensors [793a26e8]",
    //         "portraitplus_V1.0.safetensors [1400e684]",
    //         "protogenx34.safetensors [5896f8d5]",
    //         "Realistic_Vision_V1.4-pruned-fp16.safetensors [8d21810b]",
    //         "Realistic_Vision_V2.0.safetensors [79587710]",
    //         "Realistic_Vision_V4.0.safetensors [29a7afaa]",
    //         "Realistic_Vision_V5.0.safetensors [614d1063]",
    //         "Realistic_Vision_V5.1.safetensors [a0f13c83]",
    //         "redshift_diffusion-V10.safetensors [1400e684]",
    //         "revAnimated_v122.safetensors [3f4fefd9]",
    //         "rundiffusionFX25D_v10.safetensors [cd12b0ee]",
    //         "rundiffusionFX_v10.safetensors [cd4e694d]",
    //         "sdv1_4.ckpt [7460a6fa]",
    //         "v1-5-pruned-emaonly.safetensors [d7049739]",
    //         "v1-5-inpainting.safetensors [21c7ab71]",
    //         "shoninsBeautiful_v10.safetensors [25d8c546]",
    //         "theallys-mix-ii-churned.safetensors [5d9225a4]",
    //         "timeless-1.0.ckpt [7c4971d4]",
    //         "toonyou_beta6.safetensors [980f6b15]",
    //       ],
    //     },
    //     sampling_step: {
    //       value: 20,
    //       type: "slider",
    //       isAdvanceoption: true,
    //       min: 1,
    //       max: 25,
    //     },
    //     sampler: {
    //       isAdvanceoption: true,
    //       value: "DPM++ 2M Karras",
    //       type: "dropdown",
    //       options: [
    //         "DPM++ 2M Karras",
    //         "DPM++ SDE Karras",
    //         "DPM++ 2M SDE Exponential",
    //         "DPM++ 2M SDE Karras",
    //         "Euler a",
    //         "Euler",
    //         "LMS",
    //         "Heun",
    //         "DPM2",
    //         "DPM2 a",
    //         "DPM++ 2S a",
    //         "DPM++ 2M",
    //         "DPM++ SDE",
    //         "DPM++ 2M SDE",
    //         "DPM++ 2M SDE Heun",
    //         "DPM++ 2M SDE Heun Karras",
    //         "DPM++ 2M SDE Heun Exponential",
    //         "DPM++ 3M SDE",
    //         "DPM++ 3M SDE Karras",
    //         "DPM++ 3M SDE Exponential",
    //         "DPM fast",
    //         "DPM adaptive",
    //         "LMS Karras",
    //         "DPM2 Karras",
    //         "DPM2 a Karras",
    //         "DPM++ 2S a Karras",
    //         "Restart",
    //         "DDIM",
    //         "PLMS",
    //       ],
    //     },
    //     cfg_scale: {
    //       value: 7,
    //       type: "slider",
    //       isAdvanceoption: true,
    //       min: 1,
    //       max: 20,
    //     },
    //     width: {
    //       isAdvanceoption: true,
    //       value: 512,
    //       type: "slider",
    //       min: 512,
    //       max: 1536,
    //     },
    //     height: {
    //       isAdvanceoption: true,
    //       value: 512,
    //       type: "slider",
    //       min: 512,
    //       max: 1536,
    //     },
    //     seed: {
    //       type: "number",
    //       isAdvanceoption: true,
    //       value: -1,
    //     },
    //   },
    // },
  },
};

const FormPayloadSlice = createSlice({
  name: "FormPayload",
  initialState,
  reducers: {
    setElements: (state, action) => {
      state.formPayload = action.payload;
    },
  },
});

export const { setElements } = FormPayloadSlice.actions;

// export const selectFormPayload = (state) => state.FormPayload;

export default FormPayloadSlice.reducer;
